# Generated by Django 6.0.2 on 2026-03-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text='User phone number, e.g. +1 (555) 000-1234', max_length=20),
        ),
    ]
