# Generated by Django 6.0.2 on 2026-03-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_otp_code_userprofile_otp_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='currency_symbol',
            field=models.CharField(default='₹', help_text='Currency symbol for formatted notifications (e.g. ₹ or $)', max_length=5),
        ),
    ]
