# Generated by Django 6.0.2 on 2026-03-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(default='INFO', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='transaction_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
