# Generated by Django 6.0.2 on 2026-03-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
