# Generated by Django 6.0.2 on 2026-03-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
